version: "3.8"

services:
  minio:
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ${MINIO_VOLUME}:/data

  postgres:
    container_name: postgres
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

  mlflow:
    container_name: mlflow
    image: ghcr.io/mlflow/mlflow:v2.21.0
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:${MINIO_PORT}
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    command: >
      sh -c "
        pip install psycopg2-binary boto3 &&
        mkdir -p /mlruns &&
        mlflow server
          --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
          --default-artifact-root s3://${MLFLOW_BUCKET}/
          --host 0.0.0.0
          --port 5000
      "
    ports:
      - "${MLFLOW_PORT}:5000"
    depends_on:
      - postgres
      - minio
